apiVersion: v1
kind: Secret
metadata:
  name: private-repo1
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: git@github.com/keenbytes/argocd-apps-preview
  sshPrivateKey: 123
