apiVersion: v1
kind: Secret
metadata:
  name: private-repo2
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: git@github.com/keenbytes/test-repo
  sshPrivateKey: 123
