---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: a-app
  namespace: tools
spec:
  project: default
  source:
    repoURL: https://github.com/keenbytes/apps-of-apps-example
    targetRevision: HEAD
    path: app/a
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: c-set
  namespace: tools
spec:
  generators:
    - git:
        repoURL: https://github.com/keenbytes/apps-of-apps-example
        revision: HEAD
        directories:
          - path: app/c1
          - path: app/c2
  template:
    metadata:
      name: '{{path.basename}}-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/keenbytes/apps-of-apps-example
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: tools
      syncPolicy:
        automated: {}
